/**
 * Regenerates src/generated/routes.ts from the files under app/(app).
 *
 * expo-router discovers routes at build time and offers no runtime enumeration,
 * so the browsable index needs a manifest. Run after generating screens:
 *
 *   node scripts/gen-routes.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const APP = path.join(ROOT, "app", "(app)");
const OUT = path.join(ROOT, "src", "generated", "routes.ts");

/** "lead-detail-self" -> "Lead Detail Self" */
const title = (s) => s.split("-").filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join(" ");

/** All .tsx under a directory, recursively — screens nest (profile/personal-information/…). */
function walk(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (e.name.endsWith(".tsx") && !e.name.startsWith("_")) out.push(p);
  }
  return out;
}

/** Both app groups are real route trees: (app) is the influencer app, (agency) the operator app. */
const GROUPS = [
  { dir: path.join(ROOT, "app", "(app)"), prefix: "" },
  { dir: path.join(ROOT, "app", "(agency)"), prefix: "" },
];

const byFlow = new Map();
for (const g of GROUPS) {
  if (!fs.existsSync(g.dir)) continue;
  for (const file of walk(g.dir)) {
    const rel = path.relative(g.dir, file).replace(/\.tsx$/, "").split(path.sep).join("/");
    const flow = rel.split("/")[0];
    // Dynamic segments cannot be linked without a param, so skip them here.
    if (rel.includes("[")) continue;
    const slug = rel.split("/").slice(1).join("/") || flow;
    const entry = { slug, path: `/${rel}`, title: title(slug.split("/").pop() ?? slug) };
    if (!byFlow.has(flow)) byFlow.set(flow, []);
    byFlow.get(flow).push(entry);
  }
}

const flows = [...byFlow.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([flow, screens]) => ({
    flow,
    title: title(flow),
    screens: screens.sort((a, b) => a.path.localeCompare(b.path)),
  }));

const total = flows.reduce((s, f) => s + f.screens.length, 0);
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-routes.mjs — do not edit by hand.
// Run \`node scripts/gen-routes.mjs\` after adding screens.

export interface GeneratedScreen {
  slug: string;
  path: string;
  title: string;
}
export interface GeneratedFlow {
  flow: string;
  title: string;
  screens: GeneratedScreen[];
}

export const FLOWS: GeneratedFlow[] = ${JSON.stringify(flows, null, 2)};

export const TOTAL_SCREENS = ${total};
`
);
console.log(`wrote ${path.relative(ROOT, OUT)} — ${flows.length} flows, ${total} screens`);
