/**
 * Regenerates src/generated/routes.ts from the files under app/(app).
 *
 * expo-router discovers routes at build time and offers no runtime enumeration,
 * so the browsable index needs a manifest. Run after generating screens:
 *
 *   node scripts/gen-routes.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const APP = path.join(ROOT, "app", "(app)");
const OUT = path.join(ROOT, "src", "generated", "routes.ts");

/** "lead-detail-self" -> "Lead Detail Self" */
const title = (s) => s.split("-").filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join(" ");

const flows = [];
if (fs.existsSync(APP)) {
  for (const flow of fs.readdirSync(APP).sort()) {
    const dir = path.join(APP, flow);
    if (!fs.statSync(dir).isDirectory()) continue;
    const screens = fs
      .readdirSync(dir)
      .filter((f) => f.endsWith(".tsx") && !f.startsWith("_"))
      .sort()
      .map((f) => {
        const slug = f.replace(/\.tsx$/, "");
        return { slug, path: `/${flow}/${slug}`, title: title(slug) };
      });
    if (screens.length) flows.push({ flow, title: title(flow), screens });
  }
}

const total = flows.reduce((s, f) => s + f.screens.length, 0);
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-routes.mjs — do not edit by hand.
// Run \`node scripts/gen-routes.mjs\` after adding screens.

export interface GeneratedScreen {
  slug: string;
  path: string;
  title: string;
}
export interface GeneratedFlow {
  flow: string;
  title: string;
  screens: GeneratedScreen[];
}

export const FLOWS: GeneratedFlow[] = ${JSON.stringify(flows, null, 2)};

export const TOTAL_SCREENS = ${total};
`
);
console.log(`wrote ${path.relative(ROOT, OUT)} — ${flows.length} flows, ${total} screens`);
